terminator=;
continue-on-error=false
author=czhdev
logging=debug

[changeset:create_fav_wager_table]

CREATE TABLE GIS_FAV_WAGER (
    FAV_WAGER_ID   BIGINT         NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAYER_ID      VARCHAR(64)    NOT NULL,
    GROUP_NUMBER   VARCHAR(10)    NOT NULL,
    GAME_NAME      VARCHAR(64)    NOT NULL,
    WAGER_NAME     VARCHAR(255)   NOT NULL DEFAULT '',
    FLAGS          INTEGER        NOT NULL DEFAULT 0,
    CREATED_AT     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    WAGER_JSON     VARCHAR(30000) NOT NULL
);

CREATE INDEX IDX_FAV_WAGER_PLAYER ON GIS_FAV_WAGER (PLAYER_ID);
CREATE INDEX IDX_FAV_WAGER_GROUP  ON GIS_FAV_WAGER (PLAYER_ID, GROUP_NUMBER);
CREATE INDEX IDX_FAV_WAGER_GAME   ON GIS_FAV_WAGER (PLAYER_ID, GAME_NAME);

[validation:fav_wager_table_exists]

SELECT COUNT(*) FROM syscat.tables WHERE tabname='GIS_FAV_WAGER';
