package cz.bsl.czh.favourites.dao;

import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import javax.sql.DataSource;

/**
 * Lightweight Spring test configuration shared by {@link FavouritesGroupDaoTest} and
 * {@link FavouritesWagerDaoTest}. Starts an HSQLDB in-memory database using the ANSI SQL
 * driver ({@code org.hsqldb.jdbc.JDBCDriver}) — matching {@code application-test.yml} — so
 * that {@code GENERATED BY DEFAULT AS IDENTITY} DDL is accepted.
 *
 * <p>Do NOT use {@code EmbeddedDatabaseType.HSQL}: Spring maps that to the legacy
 * {@code org.hsqldb.jdbcDriver} (HSQLDB 1.x compat mode) which rejects ANSI identity columns.
 *
 * <p>Note: production delta scripts use DB2 {@code GENERATED ALWAYS AS IDENTITY}; HSQLDB
 * requires {@code GENERATED BY DEFAULT AS IDENTITY} — the DDL here is test-only.
 *
 * <p>Grep anchor: favourites
 */
@TestConfiguration
public class DaoTestConfig {

    @Bean
    public DataSource dataSource() {
        DriverManagerDataSource ds = new DriverManagerDataSource(
                "jdbc:hsqldb:mem:favourites_dao_test;DB_CLOSE_DELAY=-1", "sa", "");
        ds.setDriverClassName("org.hsqldb.jdbc.JDBCDriver");
        new ResourceDatabasePopulator(new ClassPathResource("dao-test-schema.sql")).execute(ds);
        return ds;
    }

    @Bean
    public JdbcTemplate jdbcTemplate(DataSource dataSource) {
        return new JdbcTemplate(dataSource);
    }

    @Bean
    public FavouritesGroupDao favouritesGroupDao(JdbcTemplate jdbcTemplate) {
        return new FavouritesGroupDaoImpl(jdbcTemplate);
    }

    @Bean
    public FavouritesWagerDao favouritesWagerDao(JdbcTemplate jdbcTemplate) {
        return new FavouritesWagerDaoImpl(jdbcTemplate);
    }

    @Bean
    public ObjectMapper objectMapper() {
        return JsonMapper.builder().build();
    }
}
